[WatchSAFE3.2]
PinCheck=1
Language Option=3
Cert List Mode=1
Auto Run Program Flag=0
Auto Run Program=
AutoInstallCert=1
CachePIN=1
CSPCache=1
EncodePIN=1
EKNS=0
CSPToP11=1
Exclusive_SFI=0
Extend_EEPROM=0
Hardware_Des=0
KeyType=1
KeyExchangeFirst=1
Padding_PIN=0
SWRSA=0
TokenType=1
OneContainer=0
OneCert=0
ProviderName=PROXKey CSP India V3.0
ProviderNameAll=PROXKey CSP India V3.0;PROXKey CSP India V2.0;PROXKey CSP India V1.0;
Product GUID=
P11Lib=wdpkcs.dll
NotInitialized=0
Validate Pin=1
P11Message=0
UserTool Program=WatchData\WD PROXKey\WDAdmintool.exe
UserType=2
ProductVersion=6.0.5
MaxPinLen=32
MinPinLen=6
RetryTimes=10
TokenSNLen=20
SoftKB=0
ShinCard=0
URL=https://www.e-mudhra.com/icicibank/corp/Default.aspx
FirstInsert=0
LogName32=ProxKeyLogFile.txt
LogName64=ProxKeyLogFile64.txt
;LogDir=C://
PinCacheRegName=ProxKey

;WDDEBUGAPDU=1
;WDDEBUGCSP=1
;TokenDebug=1
;WDServerOrLocalDebug=1
FTPSERV=http://proxkeyupdate.in
FTPUSERNAME=admin@proxkeyupdate.in
FTPUSERPASS=UpdateSoftware@2014#
UpdateVersion=6.0.5

UserToolWinProName=PROXKEY_Admin_Tool_ND_v34_254
UserToolWinProValue=254
g_oneUserTool=PROXKEY_Admin_TOOL_C45613C9-1234-7890-B649-19802575F456

KeyStateChangeMessage=PROXKEY ND 3.4.0 Key Status Change
P11FileMapping=PROXKEY_ND_3.4.7
P11CachePin=PROXKEY_ND_v3.4.7_Pkcs11_Cache_PIN
Downloadcertbegin=proxkey download certificate begin
Downloadcertend=proxkey download certificate end

g_oneMonitor=0xb380570d, 0xa178, 0x48da, 0xb7, 0x6a, 0xc, 0x52, 0x6a, 0xd1, 0x86, 0xd
ServiceName=SPMonitor
ServiceNameDisplay=SPMoniter V1.0
ServiceDescription=SPMoniter

g_oneWDCertM=0x3451ec03, 0x8efe, 0x45eb, 0xbc, 0x25, 0x88, 0xbb, 0xbf, 0x5b, 0xae, 0xd7
CertStatusEvent=PROXKEY_CERT_STATUS_ND_v34
SharePageFile=PROXYKEY_UDK_3.4.0_ND_PINCACHE

KeyStateChangeMessage=PROXKey CSP India V1.0_KeyStateChangeMessage
WDCertEXE=SP_CertMND.exe

[CompatibleVersion]
Number=0
;CSP1=VNPT Cryptographic Provider v3.4(UDK)

[SupportedVirtualReaderClass]
Number=1
ReaderClass1=WDIND USB CCID Key


